# Generated by Django 5.2.8 on 2025-12-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventario', models.IntegerField(default=0)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('id_veter', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
