# Generated by Django 5.2.8 on 2025-12-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del producto', max_length=500, null=True),
        ),
    ]
